spring:
    datasource:
      driverClassName: com.mysql.jdbc.Driver
      url: jdbc:mysql://localhost:3306/library
      username: root
      password: ADMIN
    jpa:
      hibernate.ddl-auto: update
      generate-ddl: true
      show-sql: true

